#TODO: use Yum repo instead of installing from source?  not sure which is better
- name: download ossec_agent source code
  get_url:
    url: 'https://github.com/ossec/ossec-hids/archive/2.8.2.tar.gz'
    dest: '/tmp'

- name: Unarchive downloaded
  shell: >
   chdir='/tmp'
   tar xvf 2.8.2.tar.gz
   creates=/tmp/ossec-hids-2.8.2

- name: copy preloaded_vars.conf
  template:
   src: 'preloaded_vars.conf'
   dest: '/tmp/ossec-hids-2.8.2/etc/preloaded-vars.conf'

- name: install.sh
  shell: >
   chdir='/tmp/ossec-hids-2.8.2'
   bash ./install.sh
   creates=/var/ossec/etc/ossec.conf

#NOTE: if authenticating to AV server via Ansible is problematic, could pull this file down locally manually
- name: pull client_keys from AV server
  fetch:
    src: '/var/ossec/etc/client.keys'
    dest: '/tmp/client.keys'
    flat: yes
  delegate_to: "{{ alientvault_server }}"

- name: copy client_keys to agent
  copy:
   src: '/tmp/client.keys'
   dest: '/tmp/client.keys'
  register: keys

- shell: >
     grep "{{ansible_default_ipv4.address}}" /tmp/client.keys  > /var/ossec/etc/client.keys
  when: keys.changed
  notify: restart ossec

- name: remove server keys
  file:
   path: '/tmp/client.keys'
   state: 'absent'

- name: start ossec
  service:
    name: 'ossec'
    state: 'started'
